version: '3.9'

services:
  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80

volumes:
  postgres-data: