version: '3.9'

services:
  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80

  goauthservice:
    image: asia-south1-docker.pkg.dev/sounish-cloud-workstation/fullstack-microservices-golang-gke/go-auth-service:v241015.4731
    restart: always
    environment:
      AUTH_SERVICE_PORT: 3000
      AUTH_SERVICE_DSN: "postgres://root:password@postgres:5432/auth?sslmode=disable"
      AUTH_SERVICE_JWT_SECRET: 5u43r5Ec2Et%455W0r4!as&(!Q)
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  goblogsservice:
    image: asia-south1-docker.pkg.dev/sounish-cloud-workstation/fullstack-microservices-golang-gke/go-blogs-service:v241015.4818
    restart: always
    environment:
      BLOGS_SERVICE_PORT: 3001
      AUTH_SERVICE_ENDPOINT: http://goauthservice:3000
      BLOGS_SERVICE_DSN: "postgres://root:password@postgres:5432/blogs?sslmode=disable"
      AUTH_SERVICE_JWT_SECRET: 5u43r5Ec2Et%455W0r4!as&(!Q)
    expose:
      - 3001
    ports:
      - 3001:3001
    depends_on:
      postgres:
        condition: service_healthy

  blogs-app-frontend:
    image: asia-south1-docker.pkg.dev/sounish-cloud-workstation/fullstack-microservices-golang-gke/blogs-app-frontend:v241000.5219
    restart: always
    environment:
      NG_APP_AUTH_SERVICE_ENDPOINT: http://goauthservice:3000
      NG_APP_BLOGS_SERVICE_ENDPOINT: http://goblogsservice:3001
    expose:
      - 80
    ports:
      - 4200:80


volumes:
  postgres-data:
