---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres-deployment"
  namespace: "fullstack-microservice-golang"
  labels:
    app: "postgres"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
      - name: "postgres"
        image: "postgres:17"
        env:
        - name: "POSTGRES_USER"
          value: "root"
        - name: "POSTGRES_PASSWORD"
          value: "password"
        - name: "POSTGRES_DB"
          value: "postgres"
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        volumeMounts:
        - name: "postgres-data"
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: "postgres-data"
        persistentVolumeClaim:
          claimName: "postgres-pvc"
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgres-pvc"
  namespace: "fullstack-microservice-golang"
  labels:
    app: "postgres"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres-service"
  namespace: "fullstack-microservice-golang"
  labels:
    app: "postgres"
spec:
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: "postgres"
  type: "ClusterIP"
---