-- CREATE database `auth`
CREATE DATABASE auth;

-- create users table
CREATE TABLE IF NOT EXISTS users (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    Username VARCHAR(25) NOT NULL UNIQUE,
    Email VARCHAR(25) NOT NULL UNIQUE,
    Password VARCHAR(128) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
	UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

-- create roles table
CREATE TABLE IF NOT EXISTS roles (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Role VARCHAR(25) NOT NULL
);

-- create user_roles table
CREATE TABLE IF NOT EXISTS user_roles (
    UserID INT NOT NULL,
    RoleID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES users(ID),
    FOREIGN KEY (RoleID) REFERENCES roles(ID)
);

-- create indexes on users table
CREATE INDEX users_username_idx ON users (Username);
CREATE INDEX users_email_idx ON users (Email);

-- create indexes on roles table
CREATE INDEX roles_role_idx ON roles (Role);

-- create indexes on user_roles table
CREATE INDEX user_roles_userid_idx ON user_roles (UserID);
CREATE INDEX user_roles_roleid_idx ON user_roles (RoleID);

-- insert roles
INSERT INTO roles (Role) VALUES ('user'), ('admin');

-- insert users
INSERT INTO users (FirstName, LastName, Username, Email, Password) VALUES 
('sounish', 'nath', 'sounishnath003', 'sounish@gmail.com', '$2a$10$1234567890abcdef01234567890abcdef$'),
('Admin', 'goauth', 'adminuser', 'admin@gmail.com', '$2a$10$1234567890abcdef01234567890abcdef$');

-- insert user roles
INSERT INTO user_roles (UserID, RoleID) VALUES 
(1, 1),
(2, 2);