----
-- auth service database
----

-- CREATE database `auth`
CREATE DATABASE auth;

-- create users table
CREATE TABLE IF NOT EXISTS users (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FirstName VARCHAR(25) NOT NULL,
    LastName VARCHAR(25) NOT NULL,
    Username VARCHAR(25) NOT NULL UNIQUE,
    Email VARCHAR(25) NOT NULL UNIQUE,
    Password VARCHAR(128) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
	UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

-- create roles table
CREATE TABLE IF NOT EXISTS roles (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Role VARCHAR(25) NOT NULL
);

-- create user_roles table
CREATE TABLE IF NOT EXISTS user_roles (
    UserID INT NOT NULL,
    RoleID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES users(ID),
    FOREIGN KEY (RoleID) REFERENCES roles(ID)
);

-- create indexes on users table
CREATE INDEX users_username_idx ON users (Username);
CREATE INDEX users_email_idx ON users (Email);

-- create indexes on roles table
CREATE INDEX roles_role_idx ON roles (Role);

-- create indexes on user_roles table
CREATE INDEX user_roles_userid_idx ON user_roles (UserID);
CREATE INDEX user_roles_roleid_idx ON user_roles (RoleID);

-- insert roles
INSERT INTO roles (Role) VALUES ('user'), ('admin');

-- insert users
INSERT INTO users (FirstName, LastName, Username, Email, Password) VALUES 
('sounish', 'nath', 'sounishnath003', 'sounish@gmail.com', '$2a$10$6PAG8iwHx9MiQ43/kpPV5uTdzYePo55cD14GglIuDUdKt222QmzlS'),
('Admin', 'goauth', 'adminuser', 'admin@gmail.com', '$2a$10$6PAG8iwHx9MiQ43/kpPV5uTdzYePo55cD14GglIuDUdKt222QmzlS');

-- insert user roles
INSERT INTO user_roles (UserID, RoleID) VALUES 
(1, 1),
(2, 2);

----
-- blogs service database
----

CREATE DATABASE blogs;

-- create blogs table
CREATE TABLE IF NOT EXISTS blogs (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    UserID INT NOT NULL,
    Title VARCHAR(25) NOT NULL,
    Subtitle VARCHAR(30) NOT NULL,
    Content TEXT NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

-- create indexes on blogs table
CREATE INDEX blogs_id_idx ON blogs (ID);
CREATE INDEX blogs_userid_idx ON blogs (UserID);
CREATE INDEX blogs_title_idx ON blogs (Title);

-- insert blogs
INSERT INTO blogs (UserID,Title,Subtitle,Content)
VALUES (1, 'My-first-blog', 'My-first-subtitle', '## Hello World 1, My Dear Friends');
INSERT INTO blogs (UserID,Title,Subtitle,Content)
VALUES (1, 'My-second-blog', 'My-second-subtitle', '## Hello World 2, My Dear Friends');